services:
  opensearch:
    image: opensearchproject/opensearch:2.16.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - skynet

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.16.0
    environment:
      - OPENSEARCH_HOSTS=[htpp://opensearch:9200]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"
    networks:
      - skynet

  app:
    build: .
    depends_on:
      - opensearch
    ports:
      - "8000:8000"
    networks:
      - skynet

networks:
  skynet:  
